---

- debug: msg="Provisioning DHCP"

- name: install dhcp package
  package:
     name:
        - dhcp
     state: latest
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version | int == 7

- name: install dhcp package
  package:
     name:
        - dhcp-server
     state: latest
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version | int == 8

- name: setup dhcpd.conf
  template:
     src: dhcpd.conf.j2
     dest: /etc/dhcp/dhcpd.conf

- name: service restart dhcpd
  service:
     name: dhcpd
     state: restarted
     enabled: yes
